### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by johnsmeeth** [jonniespratley/angular-cms#10]
I am running it well on windows but i don't know which account to login to manager? i tried with account: test/test and tried create new account too, but always see an error is undefined. Please help. thanks for creating and help.

**Comment by jonniespratley** [comment]
You need to pull the latest develop, I need to cleanup the db stuff but until then just pull.

This is assuming that you have the following commands running.

$ grunt serve
$ node server
$ sh ./bin/db.sh

You will need to register a user first.
1. Click login
2. Click Create an account
3. email: test@email.com
4. username: test
5. password: test
6. agree: true
7. submit form

Bug: goes to dashboard without logging in.

Then click login:

Login and then dashboard. I will clean this up with automation tests as well very soon.
