### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by thisboyiscrazy** [jonniespratley/angular-cms#11]
on ubuntu 14.04 i had to add:
-    "chalk": "*",
-    "grunt-karma": "~0.8.2",
-    "socket.io-client": "*",
-    "di": "*",
-    "debug": "*",
-    "log4js": "*",
-    "lodash": "*",
-    "useragent": "*",
-    "chokidar": "*",
-    "connect": "*",
-    "q": "*",
-    "source-map": "*",
-    "faye-websocket": "*",
-    "grunt-lib-contrib": "*",
-    "less": "*",
-    "mout": "*",
-    "optimist": "*"

to the depenacnes from grunt to run. after that I am still getting

> > Local Npm module "grunt-lib-contrib" not found. Is it installed?

**Comment by cyrus-za** [comment]
@thisboyiscrazy did you do npm install -g grunt-cli ?

Grunt has to be installed globally.

**Comment by thisboyiscrazy** [comment]
It is installed globally

**Comment by jonniespratley** [comment]
1. remove node modules folder
   `$ rm -rf node_modules`
2. Install dependencies
   `$ npm install`
3. Run server
   `$ grunt serve`

And you should be good, just tried and worked.
