### ISSUE TITLE
Port 9000 conflicts with XDebug

### ISSUE THREAD

**Issue by tamlyn** [jonniespratley/angular-cms#20]
When running `grunt server` I initially got the following error:

> Running "connect:livereload" (connect) task
> Fatal error: listen EACCES

Closing PHP Storm which listens on port 9000 when XDebug is enabled, allowed the app to start up correctly but now I can't open PHP Storm! Any reason for not using the standard port 3000?

I tried changing the default port in `Gruntfile.js` and discovered that the `SERVER_PORT` variable is currently unused. Got it working by changing the port again on line 88.

**Comment by jonniespratley** [comment]
Ok, sorry for the confusion, I will make sure the SERVER_PORT variable is used thru out the Gruntfile.
