### ISSUE TITLE
windows installation 

### ISSUE THREAD

**Issue by satya5561** [jonniespratley/angular-cms#6]
hi 

please tell me how to install it on windows .

**Comment by jonniespratley** [comment]
Well  first you need to install node and mongo db. Pull the repo. Run 

npm install
bower install
grunt serve

open the bin/db.sh file and run that command in another terminal

node server

Starts the API server and loads the dist version

Might need to fix the dependencies as I am having issues.

**Comment by satya5561** [comment]
i am trying to login in your sample app with your given user id and pass but is give error.

**Comment by jonniespratley** [comment]
Im sorry, you might want to change the parse api key to use a different server, but the login credentials for the demo are.

user: test
pass: test

-j
