### ISSUE TITLE
linux installation

### ISSUE THREAD

**Issue by nadavsinai** [jonniespratley/angular-cms#7]
your index.html looks for the following files with camelCased names, but in the filesystem they are called with all lowercase names :
"scripts/directives/cmswidgets.js",
"scripts/directives/cmswidget.js",
"scripts/directives/cmsuploader.js",
"scripts/directives/cmsheader.js",
scripts/directives/cmsgravatar.js"
"scripts/services/dataservice.js">,
"scripts/services/cmsdataserviceprovider.js",
"scripts/services/cmsdataservicefactory.js",
"scripts/services/cmsusersfactory.js",
"scripts/services/cmsauthservice.js",
"scripts/services/cmssessionservice.js",
"scripts/services/cmsnotify.js"

nice project

**Comment by jonniespratley** [comment]
Yes this is because the initial project scaffold was with an other version of generator-angular, I will update the generator and update the files, I also need to get around to updating the e2e tests to cover all of the views and logic. But time permits.

**Comment by jonniespratley** [comment]
I have fixed the camel cased names and is available in develop.
